#!/bin/bash
  while true; do
  sleep 10
  data=($(cat /etc/xray/config.json | grep '^#vm' | cut -d ' ' -f 2 | sort | uniq))
  if [[ ! -e /etc/limit/vmess ]]; then
  mkdir -p /etc/limit/vmess
  fi
  for akun in ${data[@]}
  do
  xray api stats --server=10085 -name "akun>>>${akun}>>>traffic>>>downlink" >& /tmp/${akun}
  getThis=$(cat /tmp/${akun} | awk '{print $1}');
  if [[ ${getThis} != "failed" ]]; then
        downlink=$(xray api stats --server=127.0.0.1:10085 -name "akun>>>${akun}>>>traffic>>>downlink" | grep -w "value" | awk '{print $2}' | cut -d '"' -f2);
        if [ -e /etc/limit/vmess/${akun} ]; then
        plus2=$(cat /etc/limit/vmess/${akun});
        if [[ ${#plus2} -gt 0 ]]; then
        plus3=$(( ${downlink} + ${plus2} ));
        echo "${plus3}" > /etc/limit/vmess/"${akun}"
        xray api stats --server=127.0.0.1:10085 -name "akun>>>${akun}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        else
        echo "${downlink}" > /etc/limit/vmess/"${akun}"
        xray api stats --server=127.0.0.1:10085 -name "akun>>>${akun}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
        else
        echo "${downlink}" > /etc/limit/vmess/"${akun}"
        xray api stats --server=127.0.0.1:10085 -name "akun>>>${akun}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
        else
      echo ""
   fi
done
# Check ur Account
for akun in ${data[@]}
  do
    if [ -e /etc/vmess/${akun} ]; then
      checkLimit=$(cat /etc/vmess/${akun});
      if [[ ${#checkLimit} -gt 1 ]]; then
      if [ -e /etc/limit/vmess/${akun} ]; then
      Usage=$(cat /etc/limit/vmess/${akun});
      if [[ ${Usage} -gt ${checkLimit} ]]; then
      exp=$(grep -w "^#vm $akun" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
      sed -i "/^#vm $akun $exp/,/^},{/d" /etc/xray/config.json
      systemctl restart xray >> /dev/null 2>&1
      else
      echo ""
      fi
      else
      echo ""
      fi
      else
      echo ""
      fi
      else
      echo ""
    fi
  done
done
