#!/bin/bash
### System Information
TANGGAL=$(date '+%Y-%m-%d')
TIMES="10"
NAMES=$(whoami)
IMP="wget -q -O"    
CHATID="isi id lu atau id gc lu"
LOCAL_DATE="/usr/bin/"
MYIP=$(wget -qO- ipinfo.io/ip)
ISP=$(wget -qO- ipinfo.io/org)
TIME=$(date +'%Y-%m-%d %H:%M:%S')
RAMMS=$(free -m | awk 'NR==2 {print $2}')
KEY=":isi token bot lu"
URL="https://api.telegram.org/bot$KEY/sendMessage"
OS=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
domen=$(cat /root/domain)
CITY=$(curl -s ipinfo.io/city )

dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
#########################
BURIQ () {
    curl -sS https://izin nya taro disini > /root/tmp
    data=( `cat /root/tmp | grep -E "^### " | awk '{print $2}'` )
    for user in "${data[@]}"
    do
    exp=( `grep -E "^### $user" "/root/tmp" | awk '{print $3}'` )
    d1=(`date -d "$exp" +%s`)
    d2=(`date -d "$biji" +%s`)
    exp2=$(( (d1 - d2) / 86400 ))
    if [[ "$exp2" -le "0" ]]; then
    echo $user > /etc/.$user.ini
    else
    rm -f  /etc/.$user.ini > /dev/null 2>&1
    fi
    done
    rm -f  /root/tmp

# sontol terbang 
MYIP=$(curl -sS ipv4.icanhazip.com)
Name=$(curl -sS https://ini juga yak lord:v | grep $MYIP | awk '{print $2}')
echo $Name > /usr/local/etc/.$Name.ini
CekOne=$(cat /usr/local/etc/.$Name.ini)

Bloman () {
if [ -f "/etc/.$Name.ini" ]; then
CekTwo=$(cat /etc/.$Name.ini)
    if [ "$CekOne" = "$CekTwo" ]; then
        res="Expired"
    fi
else
res="Permission Accepted..."
fi
mesg n || true
clear
menu
END
chmod 644 /root/.profile

if [ -f "/root/log-install.txt" ]; then
rm /root/log-install.txt > /dev/null 2>&1
fi
if [ -f "/etc/afak.conf" ]; then
rm /etc/afak.conf > /dev/null 2>&1
fi
if [ ! -f "/etc/log-create-user.log" ]; then
echo "Log All Account " > /etc/log-create-user.log
fi
history -c
echo $serverV > /opt/.ver
aureb=$(cat /home/re_otm)
b=11
if [ $aureb -gt $b ]
then
gg="PM"
else
gg="AM"
fi
curl -sS ifconfig.me > /etc/myipvps
    
    TEXT="
<u>🌀 INFO INSTALL SCRIPT 🌀</u>
<code>❇️ TIME     : </code><code>${TIME}</code>
<code>❇️ IPVPS    : </code><code>${MYIP}</code>
<code>❇️ DOMAIN   : </code><code>${domen}</code>
<code>❇️ ISP      : </code><code>${ISP}</code>
<code>❇️ LOKASI   : </code><code>${CITY}</code>
<code>❇️ USER     : </code><code>${NAMES}</code>
<code>❇️ RAM      : </code><code>${RAMMS}MB</code>
<code>❇️ LINUX    : </code><code>${OS}</code>

🛒Buy?
Cet @wikwok
🔰wikwok
"
